### ISSUE TITLE
Bluez error

### ISSUE THREAD

**Issue by hxrofo** [TarlogicSecurity/BlueSpy#10]
Hi guys
I'm facing this issue on kali nethunter
[!] Key generated
[I] The device is vulnerable!
[I] Establishing connection...
[C] bluetoothctl --timeout 2 scan on
SetDiscoveryFilter success
hci0 type 7 discovering on
Discovery started
[CHG] Controller 64:A2:F9:BD:AB:92 Discovering: yes
[NEW] Device 64:5E:9F:B9:D5:54 64-5E-9F-B9-D5-54
hci0 4C:72:74:90:0A:D8 type BR/EDR disconnected with reason 2
[CHG] Device 4C:72:74:90:0A:D8 Paired: no
[CHG] Device 4C:72:74:90:0A:D8 Connected: no

[C] bluetoothctl connect 4c:72:74:90:0a:d8
Attempting to connect to 4c:72:74:90:0a:d8
Failed to connect: org.bluez.Error.Failed br-connection-profile-unavailable

Traceback (most recent call last):
  File "/root/BlueSpy/BlueSpy.py", line 94, in <module>
    main()
  File "/root/BlueSpy/BlueSpy.py", line 78, in main
    connect(target, verbose=args.verbose)
  File "/root/BlueSpy/core.py", line 97, in connect
    run_and_check(
  File "/root/BlueSpy/system.py", line 35, in run_and_check
    raise CommandValidationException(cmdline, out)
system.CommandValidationException: ('Error while executing command "bluetoothctl connect 4c:72:74:90:0a:d8"', 'Attempting to connect to 4c:72:74:90:0a:d8\nFailed to connect: **org.bluez.Error.Failed br-connection-profile-unavailable\n')**

It works like charm on kali installed on my computer.
Thanks

**Comment by jesusgomezmoreno** [comment]
There is a thread in archlinux forum on this issue. Maybe it can help: https://bbs.archlinux.org/viewtopic.php?id=270465
