### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wolfyy59** [TarlogicSecurity/BlueSpy#15]
![441869277_1021768138946451_6381848981092479885_n](https://github.com/TarlogicSecurity/BlueSpy/assets/60975463/3a02baa9-0847-46c5-bcc2-d672d823d35b)

**Comment by jesusgomezmoreno** [comment]
This seems to be a problem with the bluetooth systemd service. Here is a thread in archlinux forum about this issue: https://bbs.archlinux.org/viewtopic.php?id=270465
